### ISSUE TITLE
No source files(s) or directory provided

### ISSUE THREAD

**Issue by anthonyonazure** [nicholasgcotton/WhisperDO#1]
I am getting this error trying to use the batch file. It doesn't matter if I use the sendto method or drag-n-drop I get the same results as if it can't read the file's attributes.

**Comment by nicholasgcotton** [comment]
Hmm. Not sure what is going on there. There's a limit in Windows related to the total length of path+filename that you can pass to a batch file (or reference at all, effectively). I believe it's 255 characters (this is why I added the directory method, as you can pass a directory and then Whisper will iterate through the audio files within regardless of how long their file names are), so maybe try putting the audio in a folder structure with a shorter total path name(s)? 

It could also be that the batch file (or user running it) doesn't have rights to pull file attributes, but that would be an unusual configuration of permissions on a Windows machine. 

If my method isn't working for you there's also [Purfview / Whisper Standalone](https://github.com/Purfview/whisper-standalone-win).

**Comment by anthonyonazure** [comment]
It's probably the path length. It's also a file in OneDrive that isn't stored locally, so maybe that is making it difficult to read. Thanks i will dig in.

**Comment by nicholasgcotton** [comment]
Oh yeah, I have no idea if OneDrive path's are available to batch files or how long their URI's might be when translated for that context. 

If you want to test %1 in a batch file refers to the first input (the file you send-to or drag-and-drop) on the batch file, so if you make a two line batch file that just says:
<code>echo %1
pause
</code>
The first line will output the URI of whatever you passed it, and the second line will just make sure the window doesn't close before you get a chance to see if. If that doesn't work then my batch file won't work either.
